### ISSUE TITLE
argparse error

### ISSUE THREAD

**Issue by b3nw** [seanthegeek/etoupdate#1]
I'm not actually sure why this is occurring, if I change -v to be -V the script runs cleanly

```
$ python --version
Python 2.7.6

t$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

```

```
$ sudo python etupdate/etupdate.py
Traceback (most recent call last):
  File "etupdate/etupdate.py", line 33, in <module>
    argparser.add_argument("--verbose", "-v", action="store_true", help="Output to the console")
  File "/usr/lib/python2.7/argparse.py", line 1297, in add_argument
    return self._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1671, in _add_action
    self._optionals._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1498, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib/python2.7/argparse.py", line 1311, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python2.7/argparse.py", line 1449, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python2.7/argparse.py", line 1456, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -v/--version: conflicting option string(s): -v
```

**Comment by seanthegeek** [comment]
Ah. It's because `-v` is already used by argparse to display the version as a built-in feature of the module. I'll push a fix. Thanks!
